import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
powerspectrum = np.fromfile('powerspectrum_task7.bin')
frequencies = np.fromfile('frequencies_task7.bin')
correlation = 1j * np.zeros(powerspectrum.shape)
N = len(powerspectrum)
for l in range(N):
    for n in range(N - 1):
        correlation[l] += powerspectrum[n]**2 * np.exp(2 * np.pi * 1j * l * n / N) / N

### plot velocity_correlations(t) ###
fig, ax = plt.subplots()
ax.plot(1e-3 * np.array([i for i in range(N)]), np.real(correlation) * 70 / max(correlation), label=r'velocity correlation')
ax.set_xlabel(r'[ps$^{-1}$]')
ax.set_ylabel(r'[A$^2$ / ps$^2$]')
ax.set_xlim(left=0.0, right=1e-3 * N / 2)

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = f'plot_task7_solid.pdf'
plt.savefig(filename)
plt.show()