import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width/1.5
fsize = 16
font = {'size': fsize}    
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read files generated by C ###
potential_energy = np.fromfile('potential_energy.txt', sep='\n')
a0 = np.fromfile('a0.txt', sep='\n')

### plot E(a) ###
fig, ax = plt.subplots()
ax.plot(a0**3, potential_energy, '.')
ax.set_xlabel(r'$a^3$ [A$^3$]')
ax.set_ylabel(r'$E_\mathrm{p}$ [eV / unit cell]')

#plt.legend()
plt.tight_layout()
filename = f'plot_task1.pdf'
plt.savefig(filename)
plt.show()