import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
mean_squared_displacements = np.fromfile('mean_squared_displacements_task5.bin')
parameters = np.fromfile('parameters_task5.bin')

### extract parameters ###
dt = parameters[0]
nbr_timesteps = int(parameters[1])
t = np.array([i * dt for i in range(nbr_timesteps)])

### plot mean_squared_displacements(t) ###
fig, ax = plt.subplots()
ax.plot(t[1:-1], mean_squared_displacements[1:-1], label=r'mean squared displacement')
ax.set_xlabel(r'$t$ [ps]')
ax.set_ylabel(r'[A^2]')

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = f'plot_task5.pdf'
plt.savefig(filename)
plt.show()