import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
msd_solid = np.loadtxt('mean_dist_solid.dat')
msd_liquid = np.loadtxt('mean_dist_liquid.dat')

### plot mean_squared_displacements(t) ###
fig, ax = plt.subplots()
ax.plot(msd_solid[:,0], msd_solid[:,1], label=r'solid')
ax.plot(msd_liquid[:,0], msd_liquid[:,1], label=r'liquid')
ax.set_xlabel(r'$t$ [ps]')
ax.set_ylabel(r'[A]')

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = f'plot_task5.pdf'
plt.savefig(filename)
plt.show()