.PHONY : all
all : stack_and_heap_allocation reducing_memory_fragmentation writing_to_files parsing_command_line_arguments naive_benchmarking

stack_and_heap_allocation : stack_and_heap_allocation.c
	gcc -o stack_and_heap_allocation stack_and_heap_allocation.c

reducing_memory_fragmentation : reducing_memory_fragmentation.c
	gcc -o reducing_memory_fragmentation reducing_memory_fragmentation.c

writing_to_files : writing_to_files.c
	gcc -o writing_to_files writing_to_files.c

parsing_command_line_arguments : parsing_command_line_arguments.c
	gcc -o parsing_command_line_arguments parsing_command_line_arguments.c

naive_benchmarking : naive_benchmarking.c
	gcc -o naive_benchmarking naive_benchmarking.c -Og
