import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
x = np.fromfile('histo_x.dat')
v = np.fromfile('histo_v.dat')

### plot mean_squared_displacements(t) ###
fig, (ax1, ax2) = plt.subplots(ncols=2)
ax1.hist(x, density=True, bins=20, color='C0', label=r'$x$ distribution')
ax2.hist(v, density=True, bins=20, color='C0', label=r'$v$ distribution')
ax1.set_xlabel(r'$x$')
ax1.set_ylabel(r'$p(x)$')
ax2.set_xlabel(r'$v$')
ax2.set_ylabel(r'$p(v)$')

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = 'histo_plot.pdf'
plt.savefig(filename)
plt.show()
