import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width/1.5
fsize = 16
font = {'size': fsize}    
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
t = np.fromfile('time.bin')
h = np.fromfile('function_output.bin')
parameters = np.fromfile('parameters.bin')

### extract parameters used ###
f = parameters[0]
a = parameters[1]
phi = parameters[2]
N = int(parameters[3])
dt = parameters[4]

### plot h(t) ###
fig, ax = plt.subplots()
ax.plot(t, h, label=r'$f = $' + f'{f:.1f}\n' +\
                    r'$a = $' + f'{a:.1f}\n' +\
                    r'$\phi = $' + f'{phi:.1f}\n' +\
                    r'$N = $' + f'{N}\n' +\
                    r'$\mathrm{d}t = $' + f'{dt:.1}')
ax.set_xlabel(r'$t$ [s]')
ax.set_ylabel(r'$h(t)$ [a]')

plt.legend()
plt.tight_layout()
filename = f'plot_task1_f={f:.1f}_a={a:.1f}_phi={phi:.1f}.pdf'
plt.savefig(filename)
plt.show()