import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
x_list = np.fromfile('x_list_task2.bin')
integrand_list = np.fromfile('integrand_list_task2.bin')
parameters = np.fromfile('parameters_task2.bin')

### extract parameters ###
N = int(parameters[0])

### plot mean_squared_displacements(t) ###
fig, ax = plt.subplots()
ax.hist(x_list, density=True, bins=20, color='C0', label=r'$x$ distribution')
x = np.linspace(0, 1)
ax.plot(x, np.sin(np.pi * x) * np.pi / 2, color='C1', label=r'$\frac{\pi}{2} \sin{\pi x}$')
ax.set_title(r'N = ' + f'{N}')
ax.set_xlabel(r'$x$')
ax.set_ylabel(r'$p(x)$')

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = f'plot_task2.pdf'
plt.savefig(filename)
plt.show()
