import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
s_from_block_average = np.fromfile('s_from_block_average_task4.bin')

### plot mean_squared_displacements(t) ###
fig, ax = plt.subplots()
ax.plot(s_from_block_average, 'o', alpha=0.1)
ax.set_xlabel(r'Block size')
ax.set_ylabel(r'$B$ Var[$F$] / Var[$f$]')

### legend & save file ###
plt.tight_layout()
filename = f'plot_task4.pdf'
plt.savefig(filename)
plt.show()
