import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import struct

### for plotting nice plots ###
width = 6
height = width / 1.5
fsize = 16
font = {'size': fsize}
mpl.rc('font', **font)
mpl.rc('xtick', labelsize=fsize)
mpl.rc('ytick', labelsize=fsize)
mpl.rc('text', usetex=False)

### read binary files generated by C ###
x = np.fromfile('histo_x.bin')
v = np.fromfile('histo_v.bin')
time = np.fromfile('time.bin')

### plot mean_squared_displacements(t) ###
dt = 1e-4
fig, (ax1, ax2) = plt.subplots(nrows=2, figsize=(16,12))
current_time_list = [0.05, 0.1, 0.15, 0.3, 1.5]
color_list = plt.cm.plasma(np.linspace(0.8, .2, len(current_time_list)))
for (current_time, color) in zip(current_time_list, color_list):
    ax1.hist(x[(time < current_time + dt) * (time > current_time)], density=True, bins=20, color=color, label=r'current_time = ' + f'{current_time:.2f}', alpha=0.4)
    ax2.hist(v[(time < current_time + dt) * (time > current_time)], density=True, bins=20, color=color, label=r'current_time = ' + f'{current_time:.2f}', alpha=0.4)

ax1.set_xlabel(r'$x$')
ax1.set_ylabel(r'$p(x)$')
ax2.set_xlabel(r'$v$')
ax2.set_ylabel(r'$p(v)$')

### legend & save file ###
plt.legend()
plt.tight_layout()
filename = 'histo_plot.pdf'
plt.savefig(filename)
plt.show()
