.PHONY : all
all : what_is_memory_sizeof what_is_memory_allocate

what_is_memory_sizeof : what_is_memory_sizeof.c
	gcc -o what_is_memory_sizeof what_is_memory_sizeof.c

what_is_memory_allocate : what_is_memory_allocate.c
	gcc -o what_is_memory_allocate what_is_memory_allocate.c
